version: 2
updates:
  # Maintain GitHub Actions used in this repo
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  # Maintain Docker base images in the root devcontainer
  - package-ecosystem: 'docker'
    directory: '/.devcontainer'
    schedule:
      interval: 'weekly'
