name: Formatting Check

on:
  push:
    branches: [main, booting]
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Run Prettier check
        run: |
          npx -y prettier@3.9.4 --check "**/*.{md,json,yml}"
